// AUTO-GENERATED by scripts/generate-design-tokens.mjs. Do not edit.
import CoreGraphics

enum ParleyDesignTokens {
    enum Light {
        static let background: UInt32 = 0xFFFFFF
        static let foreground: UInt32 = 0x0A0A0A
        static let card: UInt32 = 0xFFFFFF
        static let muted: UInt32 = 0xF5F5F5
        static let mutedForeground: UInt32 = 0x737373
        static let primary: UInt32 = 0x171717
        static let primaryForeground: UInt32 = 0xFAFAFA
        static let border: UInt32 = 0xE5E5E5
        static let destructive: UInt32 = 0xDC2626
        static let study: UInt32 = 0x7C3AED
        static let org: UInt32 = 0x0284C7
        static let warning: UInt32 = 0xD97706
        static let success: UInt32 = 0x059669
    }

    enum Dark {
        static let background: UInt32 = 0x0A0A0A
        static let foreground: UInt32 = 0xFAFAFA
        static let card: UInt32 = 0x171717
        static let muted: UInt32 = 0x262626
        static let mutedForeground: UInt32 = 0xA3A3A3
        static let primary: UInt32 = 0xE5E5E5
        static let primaryForeground: UInt32 = 0x171717
        static let border: UInt32 = 0xFFFFFF
        static let destructive: UInt32 = 0xF87171
        static let study: UInt32 = 0xA78BFA
        static let org: UInt32 = 0x38BDF8
        static let warning: UInt32 = 0xFBBF24
        static let success: UInt32 = 0x34D399
    }

    static let recording: UInt32 = 0xEF4444
    static let radius: CGFloat = 10
}
