import Foundation

/// One piece of copied text the keyboard's 📋 panel can put back.
public struct ClipboardItem: Codable, Identifiable, Equatable, Sendable {
    public var id: UUID
    public var text: String
    /// When it was last captured. A repeat capture of the same text moves the
    /// existing item here rather than adding a second one (see
    /// `ClipboardHistory.add`), so this is also the list's order and the clock
    /// expiry runs on.
    public var capturedAt: Date
    /// Pinned items sit in their own section above the recent ones and never
    /// expire. They do not count against `ClipboardHistory.maxRecent`.
    public var pinned: Bool

    public init(id: UUID = UUID(), text: String, capturedAt: Date, pinned: Bool = false) {
        self.id = id
        self.text = text
        self.capturedAt = capturedAt
        self.pinned = pinned
    }

    /// Tolerant like the lexicon's rows: a missing `pinned` is "not pinned",
    /// and only a missing text or id makes the item meaningless.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        text = try c.decode(String.self, forKey: .text)
        capturedAt = try c.decodeIfPresent(Date.self, forKey: .capturedAt) ?? .distantPast
        pinned = try c.decodeIfPresent(Bool.self, forKey: .pinned) ?? false
    }
}

/// How long an unpinned item is kept. Settings › 剪貼簿 › 保留時間.
///
/// A day by default: long enough that "the thing I copied this morning" is
/// still there after lunch, short enough that the history is not quietly a
/// record of everything someone copied this month.
public enum ClipboardRetention: String, CaseIterable, Codable, Sendable, Identifiable {
    case oneHour
    case oneDay
    case sevenDays

    public static let `default` = ClipboardRetention.oneDay

    public var id: String { rawValue }

    public var interval: TimeInterval {
        switch self {
        case .oneHour: return 60 * 60
        case .oneDay: return 24 * 60 * 60
        case .sevenDays: return 7 * 24 * 60 * 60
        }
    }
}

/// Why a piece of copied text was not kept. Never shown to the user one by one
/// — a history that explains each thing it skipped would be a list of the
/// user's secrets with labels on — but the reasons are distinct so the tests
/// can say which rule fired.
public enum ClipboardExclusion: Equatable, Sendable {
    /// Nothing but whitespace.
    case empty
    /// Longer than `ClipboardHistory.maxLength`. Skipped rather than cut: an
    /// item that inserts half of what was copied is worse than no item.
    case tooLong
    /// The pasteboard said so itself — a password manager's concealed or
    /// transient marker. See `ClipboardRules.concealedTypes`.
    case concealed
    /// Four to eight digits and nothing else: a one-time code. Useful for a
    /// minute and a liability for a day.
    case oneTimeCode
    /// No whitespace, long, and drawn from several character classes with
    /// little repetition: a token or a password. See `ClipboardRules.looksSecret`.
    case secretLike
    /// The same text as one of the user's sensitive 常用資訊 (身分證字號,
    /// 統一編號). Those are kept masked and inserted only by tap; a copy of one
    /// sitting in plain text in the clipboard history would undo that.
    case sensitiveInfo
}

/// The rules for what the clipboard history may keep. Pure functions, so the
/// whole policy is testable on a Mac with no pasteboard.
public enum ClipboardRules {
    /// Pasteboard types that mean "do not keep this", from the nspasteboard.org
    /// convention password managers follow, plus 1Password's own. A pasteboard
    /// carrying any of them is never previewed and never stored — the paste
    /// chip can still insert it, because pasting is what the user copied it
    /// for.
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public static func isConcealed(types: [String]) -> Bool {
        types.contains { concealedTypes.contains($0) }
    }

    /// Why `text` must not be kept, or `nil` when it may be.
    ///
    /// - Parameters:
    ///   - types: the pasteboard's types at the time it was read.
    ///   - blocked: the user's sensitive 常用資訊 values (`SnippetStore.sensitiveValues`).
    public static func exclusion(
        for text: String, types: [String] = [], blocked: Set<String> = []
    ) -> ClipboardExclusion? {
        if isConcealed(types: types) { return .concealed }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return .empty }
        if text.count > ClipboardHistory.maxLength { return .tooLong }
        if isOneTimeCode(trimmed) { return .oneTimeCode }
        if looksSecret(trimmed) { return .secretLike }
        if !blocked.isEmpty, blocked.contains(Snippet.normalized(trimmed)) { return .sensitiveInfo }
        return nil
    }

    /// Four to eight ASCII digits — the shape of every SMS and authenticator
    /// code. A bare number that long is rarely anything a person wants back a
    /// day later, and a code is the one thing that must not be.
    public static func isOneTimeCode(_ text: String) -> Bool {
        (4...8).contains(text.count) && text.allSatisfy { $0.isASCII && $0.isNumber }
    }

    /// A token or a password, judged from its shape alone: printable ASCII with
    /// no whitespace, at least `secretMinLength` long, mixing at least three of
    /// lowercase / uppercase / digits / symbols (two, if it is long enough to be
    /// a key — hex digests and base64 tokens often use only letters and
    /// digits), and with little repetition (Shannon entropy per character at
    /// least `secretMinEntropy`).
    ///
    /// URLs and email addresses are let through even though they match every
    /// other part of that shape: they are the most common thing anyone copies,
    /// and a history that refused them would be a history of nothing. Anything
    /// with a letter outside ASCII — Chinese text pasted without spaces, an
    /// address — is not a secret either: tokens are ASCII.
    ///
    /// It is a heuristic, and it errs towards dropping: a long product code
    /// that happens to look like a key is not kept, which costs the user one
    /// re-copy. Keeping a password for a day is the failure that matters.
    public static func looksSecret(_ text: String) -> Bool {
        guard text.count >= secretMinLength else { return false }
        guard text.unicodeScalars.allSatisfy({ $0.isASCII && $0.value > 0x20 && $0.value < 0x7F })
        else { return false }
        if looksLikeURL(text) || looksLikeEmail(text) { return false }
        var lower = false, upper = false, digit = false, symbol = false
        for scalar in text.unicodeScalars {
            switch scalar.value {
            case 0x61...0x7A: lower = true
            case 0x41...0x5A: upper = true
            case 0x30...0x39: digit = true
            default: symbol = true
            }
        }
        let classes = [lower, upper, digit, symbol].filter { $0 }.count
        let letters = lower || upper
        let enoughClasses =
            classes >= 3 || (classes == 2 && letters && digit && text.count >= secretLongLength)
        guard enoughClasses else { return false }
        return entropyPerCharacter(text) >= secretMinEntropy
    }

    public static let secretMinLength = 16
    /// Long enough that two classes are enough: a 32-character run of hex or
    /// base62 is a key, not a word.
    public static let secretLongLength = 32
    /// Bits per character. A sixteen-character string of all-different
    /// characters reaches 4.0; `aaaaaaaaaaaaaaaaB1!` stays well under 2.
    public static let secretMinEntropy = 3.0

    static func looksLikeURL(_ text: String) -> Bool {
        let lower = text.lowercased()
        if lower.hasPrefix("www.") { return true }
        guard let range = lower.range(of: "://") else { return false }
        let scheme = lower[..<range.lowerBound]
        return !scheme.isEmpty && scheme.allSatisfy { $0.isLetter || $0.isNumber || "+-.".contains($0) }
    }

    static func looksLikeEmail(_ text: String) -> Bool {
        SnippetDetector.isEmail(text)
    }

    static func entropyPerCharacter(_ text: String) -> Double {
        var counts: [Character: Int] = [:]
        for c in text { counts[c, default: 0] += 1 }
        let n = Double(text.count)
        return counts.values.reduce(0) { sum, k in
            let p = Double(k) / n
            return sum - p * log2(p)
        }
    }
}

/// The clipboard history as a value: newest first, every rule about what goes
/// in, what moves and what falls out. `ClipboardHistoryStore` is the same thing
/// with a file behind it.
public struct ClipboardHistory: Equatable, Sendable {
    /// The most unpinned items kept. The keyboard holds the whole list in
    /// memory while its panel is open, so it is a number, not a feeling: at
    /// `maxLength` each, fifty items are ~200 KB at worst, against a ~60 MB
    /// process limit.
    public static let maxRecent = 50
    /// The longest text kept, in characters.
    public static let maxLength = 2_000

    public private(set) var items: [ClipboardItem]

    public init(items: [ClipboardItem] = []) {
        self.items = items.sorted { $0.capturedAt > $1.capturedAt }
    }

    public var pinned: [ClipboardItem] { items.filter(\.pinned) }
    public var recent: [ClipboardItem] { items.filter { !$0.pinned } }

    /// Keep `text`, already cleared by `ClipboardRules`. A text already in the
    /// history is not added twice: the existing item moves to the top with a
    /// fresh stamp, keeping its id and whether it was pinned. Then the oldest
    /// unpinned items beyond `maxRecent` fall off.
    public mutating func add(_ text: String, at now: Date) {
        if let i = items.firstIndex(where: { $0.text == text }) {
            var item = items.remove(at: i)
            item.capturedAt = now
            items.insert(item, at: 0)
        } else {
            items.insert(ClipboardItem(text: text, capturedAt: now), at: 0)
        }
        capRecent()
    }

    /// Drop unpinned items older than `retention`, and anything past the cap.
    /// Pinned items are exempt from both.
    public mutating func prune(now: Date, retention: ClipboardRetention) {
        let cutoff = now.addingTimeInterval(-retention.interval)
        items.removeAll { !$0.pinned && $0.capturedAt < cutoff }
        capRecent()
    }

    public mutating func setPinned(_ id: UUID, _ pinned: Bool) {
        guard let i = items.firstIndex(where: { $0.id == id }) else { return }
        items[i].pinned = pinned
        // Unpinning puts the item back under the cap; it may be the one over.
        if !pinned { capRecent() }
    }

    public mutating func remove(_ id: UUID) {
        items.removeAll { $0.id == id }
    }

    /// Forget every item whose text is one of `values` — what saving a
    /// sensitive 常用資訊 does to a copy of it already in the history.
    public mutating func remove(matching values: Set<String>) {
        guard !values.isEmpty else { return }
        items.removeAll { values.contains(Snippet.normalized($0.text)) }
    }

    private mutating func capRecent() {
        var unpinned = 0
        items.removeAll { item in
            guard !item.pinned else { return false }
            unpinned += 1
            return unpinned > Self.maxRecent
        }
    }
}

/// The clipboard history on disk: `clipboard-history.json` in the App Group
/// container, written with `FileProtectionType.complete` (see `ProtectedFile`).
///
/// **Local only.** Nothing here touches the network, nothing is logged, and the
/// file is excluded from backup. Text only — the keyboard never reads an image
/// off the pasteboard, and neither does the app on its behalf.
///
/// Two processes write it: the keyboard (an appearance with 「自動收錄剪貼簿」
/// on, a tap on the paste chip, the panel's pin and delete) and the app (coming
/// to the front with the same setting on, and Settings' clear). Every write is
/// a read-modify-write of the whole file under a lock that only covers this
/// process; two processes writing in the same instant is the user copying in
/// one app while the other is mid-tap, and the cost of losing that race is one
/// item.
///
/// Foundation only, directory and clock injected, so it runs under `swift test`.
public final class ClipboardHistoryStore: @unchecked Sendable {
    public static let fileName = "clipboard-history.json"

    public let fileURL: URL
    private let now: @Sendable () -> Date
    private let retention: @Sendable () -> ClipboardRetention
    private let lock = NSLock()

    public init(
        directory: URL,
        now: @escaping @Sendable () -> Date = { Date() },
        retention: @escaping @Sendable () -> ClipboardRetention = { ClipboardSettings.retention() }
    ) {
        fileURL = directory.appendingPathComponent(Self.fileName)
        self.now = now
        self.retention = retention
    }

    /// The store in the App Group container, or `nil` where the container
    /// cannot be opened — a keyboard without Full Access, which shows no 📋
    /// at all for exactly that reason.
    public static func shared() -> ClipboardHistoryStore? {
        DictationChannel.container.map { ClipboardHistoryStore(directory: $0) }
    }

    /// What `capture` did.
    public enum CaptureResult: Equatable, Sendable {
        case stored
        case excluded(ClipboardExclusion)
    }

    // MARK: reading

    /// The history inside retention, newest first. Writes the pruned list back
    /// when pruning dropped anything, so an expired item does not outlive the
    /// next look at it.
    public func load() -> ClipboardHistory {
        lock.lock()
        defer { lock.unlock() }
        let stored = read()
        var history = stored
        history.prune(now: now(), retention: retention())
        if history != stored { write(history) }
        return history
    }

    // MARK: writing

    /// Keep `text` if `ClipboardRules` allows it.
    @discardableResult
    public func capture(
        _ text: String, types: [String] = [], blocked: Set<String> = []
    ) -> CaptureResult {
        if let reason = ClipboardRules.exclusion(for: text, types: types, blocked: blocked) {
            return .excluded(reason)
        }
        mutate { $0.add(text, at: now()) }
        return .stored
    }

    @discardableResult
    public func setPinned(_ id: UUID, _ pinned: Bool) -> ClipboardHistory {
        mutate { $0.setPinned(id, pinned) }
    }

    @discardableResult
    public func remove(_ id: UUID) -> ClipboardHistory {
        mutate { $0.remove(id) }
    }

    @discardableResult
    public func remove(matching values: Set<String>) -> ClipboardHistory {
        mutate { $0.remove(matching: values) }
    }

    /// 清除剪貼簿歷史: the file goes, pinned items included.
    public func clearAll() {
        lock.lock()
        defer { lock.unlock() }
        ProtectedFile.remove(fileURL)
    }

    // MARK: internals

    @discardableResult
    private func mutate(_ change: (inout ClipboardHistory) -> Void) -> ClipboardHistory {
        lock.lock()
        defer { lock.unlock() }
        var history = read()
        history.prune(now: now(), retention: retention())
        change(&history)
        write(history)
        return history
    }

    /// A missing file and an unreadable one are both an empty history — one
    /// torn write must not take the keyboard down — and a bad row costs that
    /// row only.
    private func read() -> ClipboardHistory {
        guard let data = ProtectedFile.read(fileURL),
            let rows = try? ProtectedFile.decoder.decode([LossyRow<ClipboardItem>].self, from: data)
        else { return ClipboardHistory() }
        return ClipboardHistory(items: rows.compactMap(\.value))
    }

    private func write(_ history: ClipboardHistory) {
        guard let data = try? ProtectedFile.encoder.encode(history.items) else { return }
        ProtectedFile.write(data, to: fileURL)
    }
}

/// Decodes an element or shrugs, so one bad row costs one row rather than the
/// file. The clipboard history's and the snippets' own, rather than the
/// lexicon's `Lossy`, so the three files can change independently.
struct LossyRow<T: Decodable>: Decodable {
    let value: T?

    init(from decoder: Decoder) throws {
        value = try? T(from: decoder)
    }
}
