import Foundation

/// The English pane's word list: what a part-typed word could still become,
/// and which words tend to follow a finished one.
///
/// This is the English half of what the 注音 pane got in 1.16. That pane
/// predicts from the first symbol of each syllable; this one completes the run
/// of letters before the cursor, so typing `tomo` already offers `tomorrow`
/// instead of making the user spell it. It is the one thing the system QWERTY
/// has that ours did not.
///
/// Rank is the file's order and nothing else — `scripts/gen-english-words.mjs`
/// writes 40,000 words most-frequent-first from a Google Books Ngram frequency
/// list (CC-BY 3.0; see `ios/THIRD-PARTY.md`) — so this class carries no scores.
/// What it builds at load is the *other* order: the same words sorted
/// alphabetically, with each word's file position beside it. A prefix is then a
/// contiguous range found by binary search, and the answer is the lowest-ranked
/// few words in that range.
///
/// The followers come from a second file, `english-next-words.txt`
/// (`scripts/gen-english-next-words.mjs`, Google Books 2-grams), and live in the
/// same table, so both files share one load and one warm. Each line is already
/// best first, so it is kept as written.
///
/// **Why not scan.** A linear pass over 40,000 words on every keystroke is the
/// kind of cost that turns into dropped keys on an old phone. Binary search
/// makes the search O(log n) and the walk proportional to the range, which is
/// four thousand words for a one-letter prefix and a handful by the third
/// letter — and a one-letter prefix is the only expensive case there is.
///
/// **Loaded lazily and once**, like `ZhuyinPhrases` and for the same reason:
/// this runs inside a keyboard extension, which iOS jetsams far sooner than an
/// app, so nothing is read until the user is actually typing on the English
/// pane. A keyboard opened on the voice or 注音 pane never pays for it. A
/// missing resource answers nothing, each file on its own; a keyboard that
/// crashed because a file moved would be far worse than one that stops
/// suggesting.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class EnglishWords {
    /// How many completions the bar is offered at most. Five is what fits
    /// across the strip at 17pt on the narrowest phone the keyboard runs on
    /// without the last one being clipped.
    public static let suggestionLimit = 5

    /// The resources generated by `scripts/gen-english-words.mjs` and
    /// `scripts/gen-english-next-words.mjs`.
    public static let bundled = EnglishWords(
        wordsURL: bundledWordsURL, followersURL: bundledFollowersURL)

    /// Internal rather than private so the tests can read the same files this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledWordsURL: URL? {
        Bundle.module.url(forResource: "english-words", withExtension: "txt")
    }

    static var bundledFollowersURL: URL? {
        Bundle.module.url(forResource: "english-next-words", withExtension: "txt")
    }

    /// The words in alphabetical order, and each one's position in the file,
    /// which is its frequency rank. Two parallel arrays rather than an array of
    /// pairs: the ranks are only read for the words a prefix actually matched,
    /// and keeping them out of the string array keeps that walk cache-friendly.
    private struct Table {
        let words: [String]
        let ranks: [Int32]
        let followers: [String: [String]]
    }

    private var wordsURL: URL?
    private var followersURL: URL?
    private var table: Table?
    /// A background build is on its way back to the main queue.
    private var warming = false

    /// Whether the list is in memory. Internal for the tests, which is where
    /// "did the warm arrive" is a question worth asking.
    var isWarm: Bool { table != nil }

    /// Build from words given directly, most frequent first. This is how tests
    /// get a fixture whose order they control, rather than one a corpus decides.
    /// `followers` is keyed by the lowercase previous word, best first.
    public init(words: [String], followers: [String: [String]] = [:]) {
        table = Self.indexed(words, followers: followers)
    }

    /// A `nil` or unreadable url is that half answering nothing.
    public init(wordsURL: URL?, followersURL: URL?) {
        self.wordsURL = wordsURL
        self.followersURL = followersURL
    }

    /// Build the list off the main thread, if it isn't built already.
    ///
    /// Reading 40,000 lines and sorting them is tens of milliseconds, and that
    /// must not land on the first letter the user types. The keyboard calls
    /// this when the English pane becomes current, a beat earlier and idle.
    ///
    /// A lookup that arrives first still loads synchronously. At worst the file
    /// is read twice and the later table is dropped, which costs some work in a
    /// background thread and can never hand out a half-built one.
    ///
    /// Main thread, like everything else here: the guard and the store both run
    /// there, so two warms cannot race and a warm cannot overwrite a load.
    public func warm() {
        guard table == nil, !warming, wordsURL != nil || followersURL != nil else { return }
        warming = true
        let (wordsURL, followersURL) = (wordsURL, followersURL)
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            let built = Self.parse(wordsURL: wordsURL, followersURL: followersURL)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                // A synchronous load may have beaten this here. That table is
                // the same table; replacing it would only churn memory.
                if self.table == nil { self.table = built }
            }
        }
    }

    /// The words that start with `prefix`, most frequent first.
    ///
    /// The prefix is lowercased, so case is the caller's business — see
    /// `WordSuggestions.matchingCase(of:like:)`, which is what puts it back.
    /// A word that *is* the prefix is included rather than skipped: tapping it
    /// still adds the space, which is the whole reason someone would.
    ///
    /// Empty for an empty prefix. "Every word in the language" is not a
    /// suggestion; after a space, `nextWords(after:)` is.
    public func completions(for prefix: String, limit: Int = suggestionLimit) -> [String] {
        let needle = Self.normalized(prefix)
        guard !needle.isEmpty, limit > 0 else { return [] }
        let table = load()

        // Best-so-far, kept sorted by rank. `limit` is five, so an insertion
        // into a five-element array beats any heap that could replace it.
        var best: [(rank: Int32, word: String)] = []
        var index = Self.lowerBound(of: needle, in: table.words)
        while index < table.words.count, table.words[index].hasPrefix(needle) {
            Self.offer(
                rank: table.ranks[index], word: table.words[index], to: &best, limit: limit)
            index += 1
        }
        return best.map(\.word)
    }

    /// The word's frequency rank, or `nil` if it is not in the list. Exact
    /// match, normalized the way `completions` normalizes a prefix.
    func rank(of word: String) -> Int? {
        let needle = Self.normalized(word)
        guard !needle.isEmpty else { return nil }
        let table = load()
        let index = Self.lowerBound(of: needle, in: table.words)
        guard index < table.words.count, table.words[index] == needle else { return nil }
        return Int(table.ranks[index])
    }

    /// The words that most often follow `word`, best first, in the data's own
    /// case (`I`, `York`). Empty for a word the table has no line for.
    public func nextWords(after word: String, limit: Int = suggestionLimit) -> [String] {
        guard limit > 0 else { return [] }
        return Array(load().followers[Self.normalized(word)]?.prefix(limit) ?? [])
    }

    /// Put a candidate into the running best-of list, if it earns a place.
    private static func offer(
        rank: Int32, word: String, to best: inout [(rank: Int32, word: String)], limit: Int
    ) {
        if best.count == limit, let last = best.last, rank >= last.rank { return }
        let at = best.firstIndex { $0.rank > rank } ?? best.count
        best.insert((rank, word), at: at)
        if best.count > limit { best.removeLast() }
    }

    /// The first index whose word is not ordered before `needle`.
    ///
    /// Plain `String` comparison, which for the ASCII letters and apostrophes
    /// this list is made of is byte order — and byte order is what makes every
    /// word sharing a prefix a contiguous run. The generator guarantees the
    /// alphabet; a prefix outside it simply matches nothing.
    private static func lowerBound(of needle: String, in words: [String]) -> Int {
        var low = 0
        var high = words.count
        while low < high {
            let mid = low + (high - low) / 2
            if words[mid] < needle { low = mid + 1 } else { high = mid }
        }
        return low
    }

    /// Lowercased, and with a typographic apostrophe folded to the plain one iOS
    /// smart quotes replace. A user who typed `don’t` in a field with smart
    /// quotes on is asking the same question as one who typed `don't`.
    static func normalized(_ prefix: String) -> String {
        prefix.lowercased().replacingOccurrences(of: "\u{2019}", with: "'")
    }

    // MARK: the table

    private static func indexed(_ words: [String], followers: [String: [String]]) -> Table {
        // Rank before sorting: the order they arrive in *is* the rank.
        let ranked = words.enumerated().map { (word: $0.element, rank: Int32($0.offset)) }
            .sorted { $0.word < $1.word }
        return Table(
            words: ranked.map(\.word), ranks: ranked.map(\.rank),
            followers: Dictionary(
                followers.map { (normalized($0.key), $0.value) }, uniquingKeysWith: { first, _ in first }))
    }

    private func load() -> Table {
        if let table { return table }
        // A failed read caches the empty table too, so a missing resource costs
        // one attempt rather than one per keystroke.
        let built = Self.parse(wordsURL: wordsURL, followersURL: followersURL)
        table = built
        return built
    }

    private static func parse(wordsURL: URL?, followersURL: URL?) -> Table {
        var words: [String] = []
        words.reserveCapacity(48_000)
        for line in lines(of: wordsURL) { words.append(String(line)) }
        var followers: [String: [String]] = [:]
        for line in lines(of: followersURL) {
            let fields = line.split(separator: " ").map(String.init)
            guard let previous = fields.first, fields.count > 1 else { continue }
            followers[previous] = Array(fields.dropFirst())
        }
        return indexed(words, followers: followers)
    }

    private static func lines(of url: URL?) -> [Substring] {
        guard let url, let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
        return text.split(separator: "\n", omittingEmptySubsequences: true)
            .filter { !$0.hasPrefix("#") }
    }
}
