import Foundation

/// The English pane's word list: what a part-typed word could still become.
///
/// This is the English half of what the 注音 pane got in 1.16. That pane
/// predicts from the first symbol of each syllable; this one completes the run
/// of letters before the cursor, so typing `tomo` already offers `tomorrow`
/// instead of making the user spell it. It is the one thing the system QWERTY
/// has that ours did not.
///
/// Rank is the file's order and nothing else — `scripts/gen-english-words.mjs`
/// writes 40,000 words most-frequent-first from a Google Books Ngram frequency
/// list (CC-BY 3.0; see `ios/THIRD-PARTY.md`) — so this class carries no scores.
/// What it builds at load is the *other* order: the same words sorted
/// alphabetically, with each word's file position beside it. A prefix is then a
/// contiguous range found by binary search, and the answer is the lowest-ranked
/// few words in that range.
///
/// **Why not scan.** A linear pass over 40,000 words on every keystroke is the
/// kind of cost that turns into dropped keys on an old phone. Binary search
/// makes the search O(log n) and the walk proportional to the range, which is
/// four thousand words for a one-letter prefix and a handful by the third
/// letter — and a one-letter prefix is the only expensive case there is.
///
/// **Loaded lazily, never twice at once, and dropped under pressure**, like
/// `ZhuyinPhrases` and for the same reason: this runs inside a keyboard
/// extension, which iOS jetsams far sooner than an app, so nothing is read until
/// the user is actually on the English pane. A keyboard opened on the voice or
/// 注音 pane never pays for it. A missing resource answers no completions; a
/// keyboard that crashed because a file moved would be far worse than one that
/// stops suggesting.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class EnglishWords {
    /// How many completions the bar is offered at most. Five is what fits
    /// across the strip at 17pt on the narrowest phone the keyboard runs on
    /// without the last one being clipped.
    public static let suggestionLimit = 5

    /// The resource generated by `scripts/gen-english-words.mjs`.
    public static let bundled = EnglishWords(url: bundledURL)

    /// Internal rather than private so the tests can read the same file this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledURL: URL? {
        Bundle.module.url(forResource: "english-words", withExtension: "txt")
    }

    /// The words in alphabetical order, and each one's position in the file,
    /// which is its frequency rank. Two parallel arrays rather than an array of
    /// pairs: the ranks are only read for the words a prefix actually matched,
    /// and keeping them out of the string array keeps that walk cache-friendly.
    private struct Table {
        let words: [String]
        let ranks: [Int32]
    }

    private var url: URL?
    private var table: Table?
    /// A background build is on its way back to the main queue.
    private var warming = false
    /// Everyone who asked `warm` to be told when the table lands, oldest first.
    private var onReady: [() -> Void] = []

    /// Whether the list is in memory. Internal for the tests, which is where
    /// "did the warm arrive" is a question worth asking.
    var isWarm: Bool { table != nil }

    /// How many times the resource has been parsed. Internal for the tests,
    /// which is where "was a second table ever built" is a question worth
    /// asking.
    private(set) var parseCount = 0

    /// Build from words given directly, most frequent first. This is how tests
    /// get a fixture whose order they control, rather than one a corpus decides.
    public init(words: [String]) {
        table = Self.indexed(words)
    }

    /// A `nil` url is a list that answers nothing.
    public init(url: URL?) {
        self.url = url
    }

    /// Build the list off the main thread, if it isn't built already, and call
    /// `onReady` on the main queue once it is — straight away when it already
    /// is, or when there is no resource to wait for.
    ///
    /// Reading 40,000 lines and sorting them is tens of milliseconds, and that
    /// must not land on the first letter the user types. The keyboard calls
    /// this when the English pane becomes current, a beat earlier and idle.
    ///
    /// A lookup that arrives while the warm is in flight answers nothing rather
    /// than reading a second copy beside it — the same rule, and the same
    /// preventive reason, as `ZhuyinPhrases.warm(onReady:)`. The bar is blank
    /// for that letter; `onReady` is how the caller fills it in.
    ///
    /// Main thread, like everything else here: the guard, the store and the
    /// completions all run there, so two warms cannot race and a lookup can
    /// never see half a list.
    public func warm(onReady: (() -> Void)? = nil) {
        guard table == nil, let url else {
            onReady?()
            return
        }
        if let onReady { self.onReady.append(onReady) }
        guard !warming else { return }
        warming = true
        parseCount += 1
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            // Nothing on `self` is touched off the main queue — the parse is a
            // function of the URL alone.
            let built = Self.parse(url)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                // Nothing can have filled this meanwhile — `load` does not read
                // while a warm is in flight — so the guard is only a backstop.
                if self.table == nil { self.table = built }
                let waiting = self.onReady
                self.onReady = []
                waiting.forEach { $0() }
            }
        }
    }

    /// Give the list back, so the next lookup reads the resource again.
    ///
    /// For memory pressure: the keyboard calls this from
    /// `didReceiveMemoryWarning`. The next lookup reads the file again
    /// synchronously, which is one slow letter rather than a killed keyboard.
    ///
    /// A no-op while a warm is in flight — it would land a moment later anyway,
    /// and dropping it here would only mean parsing again — and for a list
    /// built from words, which has nothing to reload from.
    public func unload() {
        guard !warming, url != nil else { return }
        table = nil
    }

    /// The words that start with `prefix`, most frequent first.
    ///
    /// The prefix is lowercased, so case is the caller's business — see
    /// `WordSuggestions.matchingCase(of:like:)`, which is what puts it back.
    /// A word that *is* the prefix is included rather than skipped: tapping it
    /// still adds the space, which is the whole reason someone would.
    ///
    /// Empty for an empty prefix. "Every word in the language" is not a
    /// suggestion, and the strip goes back to the wordmark.
    public func completions(for prefix: String, limit: Int = suggestionLimit) -> [String] {
        let needle = Self.normalized(prefix)
        guard !needle.isEmpty, limit > 0 else { return [] }
        let table = load()

        // Best-so-far, kept sorted by rank. `limit` is five, so an insertion
        // into a five-element array beats any heap that could replace it.
        var best: [(rank: Int32, word: String)] = []
        var index = Self.lowerBound(of: needle, in: table.words)
        while index < table.words.count, table.words[index].hasPrefix(needle) {
            Self.offer(
                rank: table.ranks[index], word: table.words[index], to: &best, limit: limit)
            index += 1
        }
        return best.map(\.word)
    }

    /// Put a candidate into the running best-of list, if it earns a place.
    private static func offer(
        rank: Int32, word: String, to best: inout [(rank: Int32, word: String)], limit: Int
    ) {
        if best.count == limit, let last = best.last, rank >= last.rank { return }
        let at = best.firstIndex { $0.rank > rank } ?? best.count
        best.insert((rank, word), at: at)
        if best.count > limit { best.removeLast() }
    }

    /// The first index whose word is not ordered before `needle`.
    ///
    /// Plain `String` comparison, which for the ASCII letters and apostrophes
    /// this list is made of is byte order — and byte order is what makes every
    /// word sharing a prefix a contiguous run. The generator guarantees the
    /// alphabet; a prefix outside it simply matches nothing.
    private static func lowerBound(of needle: String, in words: [String]) -> Int {
        var low = 0
        var high = words.count
        while low < high {
            let mid = low + (high - low) / 2
            if words[mid] < needle { low = mid + 1 } else { high = mid }
        }
        return low
    }

    /// Lowercased, and with a typographic apostrophe folded to the plain one iOS
    /// smart quotes replace. A user who typed `don’t` in a field with smart
    /// quotes on is asking the same question as one who typed `don't`.
    private static func normalized(_ prefix: String) -> String {
        prefix.lowercased().replacingOccurrences(of: "\u{2019}", with: "'")
    }

    // MARK: the table

    private static func indexed(_ words: [String]) -> Table {
        // Rank before sorting: the order they arrive in *is* the rank.
        let ranked = words.enumerated().map { (word: $0.element, rank: Int32($0.offset)) }
            .sorted { $0.word < $1.word }
        return Table(words: ranked.map(\.word), ranks: ranked.map(\.rank))
    }

    private func load() -> Table {
        if let table { return table }
        // Never a second read beside the one in flight — see `warm`.
        if warming { return Table(words: [], ranks: []) }
        // A failed read caches the empty table too, so a missing resource costs
        // one attempt rather than one per keystroke.
        if url != nil { parseCount += 1 }
        let built = url.map(Self.parse) ?? Table(words: [], ranks: [])
        table = built
        return built
    }

    /// Read and index the resource. Static, and a function of the URL alone, so
    /// `warm` can run it on a background queue without touching this instance.
    private static func parse(_ url: URL) -> Table {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            return Table(words: [], ranks: [])
        }
        var words: [String] = []
        words.reserveCapacity(48_000)
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            guard !line.hasPrefix("#") else { continue }
            words.append(String(line))
        }
        // The file's string goes out of scope here.
        return indexed(words)
    }
}
