import Foundation

/// The English pane's word list: what a part-typed word could still become,
/// and which words tend to follow a finished one.
///
/// This is the English half of what the 注音 pane got in 1.16. That pane
/// predicts from the first symbol of each syllable; this one completes the run
/// of letters before the cursor, so typing `tomo` already offers `tomorrow`
/// instead of making the user spell it. It is the one thing the system QWERTY
/// has that ours did not.
///
/// Rank is the file's order and nothing else — `scripts/gen-english-words.mjs`
/// writes 40,000 words most-frequent-first from a Google Books Ngram frequency
/// list (CC-BY 3.0; see `ios/THIRD-PARTY.md`) — so this class carries no scores.
/// What it builds at load is the *other* order: the same words sorted
/// alphabetically, with each word's file position beside it. A prefix is then a
/// contiguous range found by binary search, and the answer is the lowest-ranked
/// few words in that range.
///
/// The followers come from a second file, `english-next-words.txt`
/// (`scripts/gen-english-next-words.mjs`, Google Books 2-grams), and live in the
/// same table, so both files share one load and one warm. Each line is already
/// best first, so it is kept as written.
///
/// **Why not scan.** A linear pass over 40,000 words on every keystroke is the
/// kind of cost that turns into dropped keys on an old phone. Binary search
/// makes the search O(log n) and the walk proportional to the range, which is
/// four thousand words for a one-letter prefix and a handful by the third
/// letter. The one- and two-letter prefixes — the only expensive walks, and
/// the first two keys of every word typed — are answered from a table built
/// once at load instead (`Table.shortPrefixes`), so no keystroke walks more
/// than a three-letter range.
///
/// **Loaded lazily, never twice at once, and dropped under pressure**, like
/// `ZhuyinPhrases` and for the same reason: this runs inside a keyboard
/// extension, which iOS jetsams far sooner than an app, so nothing is read until
/// the user is actually on the English pane. A keyboard opened on the voice or
/// 注音 pane never pays for it. A missing resource answers nothing, each file on
/// its own; a keyboard that crashed because a file moved would be far worse
/// than one that stops suggesting.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class EnglishWords {
    /// How many completions the bar is offered at most. Five is what fits
    /// across the strip at 17pt on the narrowest phone the keyboard runs on
    /// without the last one being clipped.
    public static let suggestionLimit = 5

    /// The resources generated by `scripts/gen-english-words.mjs` and
    /// `scripts/gen-english-next-words.mjs`.
    public static let bundled = EnglishWords(
        wordsURL: bundledWordsURL, followersURL: bundledFollowersURL)

    /// Internal rather than private so the tests can read the same files this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledWordsURL: URL? {
        Bundle.module.url(forResource: "english-words", withExtension: "txt")
    }

    static var bundledFollowersURL: URL? {
        Bundle.module.url(forResource: "english-next-words", withExtension: "txt")
    }

    /// The words in alphabetical order, and each one's position in the file,
    /// which is its frequency rank. Two parallel arrays rather than an array of
    /// pairs: the ranks are only read for the words a prefix actually matched,
    /// and keeping them out of the string array keeps that walk cache-friendly.
    private struct Table {
        let words: [String]
        let ranks: [Int32]
        let followers: [String: [String]]
        /// Each previous word's followers keyed by their lowercase form, the
        /// first follower kept where two fold to the same key. It is what
        /// `WordSuggestions.split` asks — "does this word follow that one,
        /// whatever its case" — and it used to answer by copying the whole
        /// follower list and lowercasing every entry, once per cut, on most
        /// keystrokes in the middle of a word.
        let followersByLowercase: [String: [String: String]]
        /// The best `suggestionLimit` completions of every one- and two-letter
        /// prefix any word starts with, computed by the very walk `completions`
        /// does, so the answer is the same by construction. A one-letter prefix
        /// walks four or five thousand words (`s`, `c`, `p`); a two-letter one
        /// several hundred; and they are the first two keys of every word
        /// typed. A few hundred entries of five short strings each.
        let shortPrefixes: [String: [String]]
    }

    /// The longest prefix `Table.shortPrefixes` answers, in characters.
    private static let shortPrefixLength = 2

    private var wordsURL: URL?
    private var followersURL: URL?
    /// Whether either file is there to read. A list built from words, or from
    /// no files at all, has nothing to warm or to reload.
    private var hasResource: Bool { wordsURL != nil || followersURL != nil }
    private var table: Table?
    /// A background build is on its way back to the main queue.
    private var warming = false
    /// Everyone who asked `warm` to be told when the table lands, oldest first.
    private var onReady: [() -> Void] = []

    /// Whether the list is in memory. Internal for the tests, which is where
    /// "did the warm arrive" is a question worth asking.
    var isWarm: Bool { table != nil }

    /// How many times the resource has been parsed. Internal for the tests,
    /// which is where "was a second table ever built" is a question worth
    /// asking.
    private(set) var parseCount = 0

    /// Build from words given directly, most frequent first. This is how tests
    /// get a fixture whose order they control, rather than one a corpus decides.
    /// `followers` is keyed by the lowercase previous word, best first.
    public init(words: [String], followers: [String: [String]] = [:]) {
        table = Self.indexed(words, followers: followers)
    }

    /// A `nil` or unreadable url is that half answering nothing.
    public init(wordsURL: URL?, followersURL: URL?) {
        self.wordsURL = wordsURL
        self.followersURL = followersURL
    }

    /// Build the list off the main thread, if it isn't built already, and call
    /// `onReady` on the main queue once it is — straight away when it already
    /// is, or when there is no resource to wait for.
    ///
    /// Reading 40,000 lines and sorting them is tens of milliseconds, and that
    /// must not land on the first letter the user types. The keyboard calls
    /// this when the English pane becomes current, a beat earlier and idle.
    ///
    /// A lookup that arrives while the warm is in flight answers nothing rather
    /// than reading a second copy beside it — the same rule, and the same
    /// preventive reason, as `ZhuyinPhrases.warm(onReady:)`. It matters more
    /// here than for completions alone: the pane refreshes its bar in the same
    /// turn it calls this, and after a space that refresh asks for predictions.
    /// The bar is blank for that moment; `onReady` is how the caller fills it in.
    ///
    /// Main thread, like everything else here: the guard, the store and the
    /// completions all run there, so two warms cannot race and a lookup can
    /// never see half a table.
    public func warm(onReady: (() -> Void)? = nil) {
        guard table == nil, hasResource else {
            onReady?()
            return
        }
        if let onReady { self.onReady.append(onReady) }
        guard !warming else { return }
        warming = true
        parseCount += 1
        let (wordsURL, followersURL) = (wordsURL, followersURL)
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            let built = Self.parse(wordsURL: wordsURL, followersURL: followersURL)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                // Nothing can have filled this meanwhile — `load` does not read
                // while a warm is in flight — so the guard is only a backstop.
                if self.table == nil { self.table = built }
                let waiting = self.onReady
                self.onReady = []
                waiting.forEach { $0() }
            }
        }
    }

    /// Give the list back, so the next lookup reads the resource again.
    ///
    /// For memory pressure: the keyboard calls this from
    /// `didReceiveMemoryWarning`. The next lookup reads the files again
    /// synchronously, which is one slow letter rather than a killed keyboard.
    ///
    /// A no-op while a warm is in flight — it would land a moment later anyway,
    /// and dropping it here would only mean parsing again — and for a list
    /// built from words, which has nothing to reload from.
    public func unload() {
        guard !warming, hasResource else { return }
        table = nil
    }

    /// The words that start with `prefix`, most frequent first.
    ///
    /// The prefix is lowercased, so case is the caller's business — see
    /// `WordSuggestions.matchingCase(of:like:)`, which is what puts it back.
    /// A word that *is* the prefix is included rather than skipped: tapping it
    /// still adds the space, which is the whole reason someone would.
    ///
    /// Empty for an empty prefix. "Every word in the language" is not a
    /// suggestion; after a space, `nextWords(after:)` is.
    public func completions(for prefix: String, limit: Int = suggestionLimit) -> [String] {
        completions(forNormalized: Self.normalized(prefix), limit: limit)
    }

    /// `completions(for:limit:)` for a prefix the caller has already put
    /// through `normalized`, so a caller that needs the normalized form for
    /// something else as well does not build it twice per keystroke.
    func completions(forNormalized needle: String, limit: Int = suggestionLimit) -> [String] {
        guard !needle.isEmpty, limit > 0, let table = load() else { return [] }
        // The table holds the top `suggestionLimit` in rank order, so any
        // smaller limit is its front. A larger one — no caller asks for it —
        // walks, as does a prefix no word starts with.
        if limit <= Self.suggestionLimit, let known = table.shortPrefixes[needle] {
            return Array(known.prefix(limit))
        }
        return Self.walk(needle, in: table.words, ranks: table.ranks, limit: limit)
    }

    /// The best `limit` words in the alphabetical range sharing `needle`.
    private static func walk(
        _ needle: String, in words: [String], ranks: [Int32], limit: Int
    ) -> [String] {
        // Best-so-far, kept sorted by rank. `limit` is five, so an insertion
        // into a five-element array beats any heap that could replace it.
        var best: [(rank: Int32, word: String)] = []
        var index = lowerBound(of: needle, in: words)
        while index < words.count, words[index].hasPrefix(needle) {
            offer(rank: ranks[index], word: words[index], to: &best, limit: limit)
            index += 1
        }
        return best.map(\.word)
    }

    /// The word's frequency rank, or `nil` if it is not in the list. Exact
    /// match, normalized the way `completions` normalizes a prefix.
    func rank(of word: String) -> Int? {
        rank(ofNormalized: Self.normalized(word))
    }

    /// `rank(of:)` for a word already put through `normalized`.
    func rank(ofNormalized needle: String) -> Int? {
        guard !needle.isEmpty, let table = load() else { return nil }
        let index = Self.lowerBound(of: needle, in: table.words)
        guard index < table.words.count, table.words[index] == needle else { return nil }
        return Int(table.ranks[index])
    }

    /// The words that most often follow `word`, best first, in the data's own
    /// case (`I`, `York`). Empty for a word the table has no line for.
    public func nextWords(after word: String, limit: Int = suggestionLimit) -> [String] {
        guard limit > 0, let table = load() else { return [] }
        return Array(table.followers[Self.normalized(word)]?.prefix(limit) ?? [])
    }

    /// The follower of `previous` whose lowercase form is `lowercased`, in the
    /// data's own case, or `nil` if the table has no such pair. Both arguments
    /// already normalized. The first match in best-first order, which is what
    /// scanning `nextWords(after:limit: .max)` for it would find — without the
    /// copy and without lowercasing every follower to compare.
    func follower(ofNormalized previous: String, lowercased: String) -> String? {
        load()?.followersByLowercase[previous]?[lowercased]
    }

    /// Put a candidate into the running best-of list, if it earns a place.
    private static func offer(
        rank: Int32, word: String, to best: inout [(rank: Int32, word: String)], limit: Int
    ) {
        if best.count == limit, let last = best.last, rank >= last.rank { return }
        let at = best.firstIndex { $0.rank > rank } ?? best.count
        best.insert((rank, word), at: at)
        if best.count > limit { best.removeLast() }
    }

    /// The first index whose word is not ordered before `needle`.
    ///
    /// Plain `String` comparison, which for the ASCII letters and apostrophes
    /// this list is made of is byte order — and byte order is what makes every
    /// word sharing a prefix a contiguous run. The generator guarantees the
    /// alphabet; a prefix outside it simply matches nothing.
    private static func lowerBound(of needle: String, in words: [String]) -> Int {
        var low = 0
        var high = words.count
        while low < high {
            let mid = low + (high - low) / 2
            if words[mid] < needle { low = mid + 1 } else { high = mid }
        }
        return low
    }

    /// Lowercased, and with a typographic apostrophe folded to the plain one iOS
    /// smart quotes replace. A user who typed `don’t` in a field with smart
    /// quotes on is asking the same question as one who typed `don't`.
    static func normalized(_ prefix: String) -> String {
        foldingApostrophes(prefix.lowercased())
    }

    /// The apostrophe half of `normalized`, for a caller that already holds the
    /// lowercased string. Most words have no typographic apostrophe, and for
    /// them this hands the string back rather than copying it through a
    /// Foundation search that finds nothing.
    static func foldingApostrophes(_ lowercased: String) -> String {
        guard lowercased.unicodeScalars.contains("\u{2019}") else { return lowercased }
        return lowercased.replacingOccurrences(of: "\u{2019}", with: "'")
    }

    // MARK: the table

    private static func indexed(_ words: [String], followers: [String: [String]]) -> Table {
        // Rank before sorting: the order they arrive in *is* the rank.
        let ranked = words.enumerated().map { (word: $0.element, rank: Int32($0.offset)) }
            .sorted { $0.word < $1.word }
        let sorted = ranked.map(\.word)
        let ranks = ranked.map(\.rank)
        let followers = Dictionary(
            followers.map { (normalized($0.key), $0.value) }, uniquingKeysWith: { first, _ in first })
        return Table(
            words: sorted, ranks: ranks, followers: followers,
            followersByLowercase: followers.mapValues { list in
                var byLowercase: [String: String] = [:]
                byLowercase.reserveCapacity(list.count)
                for follower in list where byLowercase[follower.lowercased()] == nil {
                    byLowercase[follower.lowercased()] = follower
                }
                return byLowercase
            },
            shortPrefixes: shortPrefixTable(sorted, ranks: ranks))
    }

    /// `Table.shortPrefixes`: the walk's answer for every one- and two-letter
    /// prefix a word actually starts with. A prefix nothing starts with is left
    /// out and walks — which finds nothing, at the cost of one binary search.
    ///
    /// The words are sorted, so each word's prefixes are compared with the
    /// previous word's rather than collected into a set: about 40,000 cheap
    /// comparisons and some seven hundred walks, whose ranges add up to the
    /// list twice over. Measured at about two milliseconds on top of a ~13 ms
    /// parse (release build, Apple silicon Mac), on the warm's background
    /// thread — and it is why no keystroke walks a one-letter range any more.
    private static func shortPrefixTable(_ words: [String], ranks: [Int32]) -> [String: [String]] {
        var table: [String: [String]] = [:]
        // The previous word's prefix at each length, index 0 for one letter.
        var previous = [Substring](repeating: "", count: shortPrefixLength)
        for word in words {
            for length in 1...shortPrefixLength {
                let prefix = word.prefix(length)
                guard prefix.count == length else { break }
                if previous[length - 1] == prefix { continue }
                previous[length - 1] = prefix
                let key = String(prefix)
                if table[key] == nil {
                    table[key] = walk(key, in: words, ranks: ranks, limit: suggestionLimit)
                }
            }
        }
        return table
    }

    /// `nil` while a warm is in flight.
    private func load() -> Table? {
        if let table { return table }
        // Never a second read beside the one in flight — see `warm`.
        guard !warming else { return nil }
        // A failed read caches the empty table too, so a missing resource costs
        // one attempt rather than one per keystroke.
        if hasResource { parseCount += 1 }
        let built = Self.parse(wordsURL: wordsURL, followersURL: followersURL)
        table = built
        return built
    }

    private static func parse(wordsURL: URL?, followersURL: URL?) -> Table {
        var words: [String] = []
        words.reserveCapacity(48_000)
        for line in lines(of: wordsURL) { words.append(String(line)) }
        var followers: [String: [String]] = [:]
        for line in lines(of: followersURL) {
            let fields = line.split(separator: " ").map(String.init)
            guard let previous = fields.first, fields.count > 1 else { continue }
            followers[previous] = Array(fields.dropFirst())
        }
        return indexed(words, followers: followers)
    }

    private static func lines(of url: URL?) -> [Substring] {
        guard let url, let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
        return text.split(separator: "\n", omittingEmptySubsequences: true)
            .filter { !$0.hasPrefix("#") }
    }
}
