import Foundation

/// The 注音 pane's associated phrases (聯想詞): after a candidate is picked and
/// nothing is left to type, what usually comes next.
///
/// Pick 研 and the strip offers 究, 發, 判 …; pick 究 from there and it offers
/// what follows 研究 — 所, 院, 生 — and then what follows 究. That is McBopomofo's
/// associated-phrase feature, and the table is derived the way their
/// `associated-phrases-v2.txt` is (`scripts/gen-zhuyin-associations.mjs`):
/// every corpus phrase filed under its first character, best first, sixty at
/// most. One row per character, the continuations — the phrase without its
/// first character — space separated, so a row is one string and a lookup
/// splits only the rows it reads.
///
/// **A lookup reads the longest suffix first.** What was just committed is
/// matched three characters back, then two, then one: after 研究 the rows
/// under 研 whose continuation starts with 究 come first (所, 院, 生 …), and
/// the plain associations of 究 follow. So a chain of taps keeps following one
/// phrase for as long as the table has it, and still has something to say
/// when it does not.
///
/// **Loaded lazily, never twice at once, and dropped under pressure** — the
/// same contract as `ZhuyinPhrases`, for the same reason. About 3,500 rows,
/// 190 KB of text; a few hundred kilobytes resident (measured in the tests).
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class ZhuyinAssociations {
    /// The resource generated by `scripts/gen-zhuyin-associations.mjs`.
    public static let bundled = ZhuyinAssociations(url: bundledURL)

    static var bundledURL: URL? {
        Bundle.module.url(forResource: "zhuyin-associations", withExtension: "txt")
    }

    /// How many a lookup returns. The strip draws thirty
    /// (`StripBar.drawnLimit`) and there is no grid behind these, so a longer
    /// list would only be work nobody sees.
    public static let limit = 30

    /// How far back a lookup reads what was committed. Four-character phrases
    /// are the longest in the table, so three characters of context is the
    /// most that can still leave something to continue with.
    static let maxContext = 3

    private var url: URL?
    private var table: [Character: String]?
    private var warming = false
    private var onReady: [() -> Void] = []

    var isWarm: Bool { table != nil }

    /// As `ZhuyinPhrases.parsesOnLookup`: the keyboard turns it off, so a
    /// lookup that finds nothing loaded warms instead of parsing on a key.
    public var parsesOnLookup = true

    /// Build from rows given directly — character to continuations, best
    /// first. For tests.
    public init(entries: [Character: [String]]) {
        table = entries.mapValues { $0.joined(separator: " ") }
    }

    /// A `nil` url is a table that answers nothing.
    public init(url: URL?) {
        self.url = url
    }

    /// Read the table off the main thread, if it is not read, and call
    /// `onReady` on the main queue once it is. See `ZhuyinPhrases.warm`.
    public func warm(onReady: (() -> Void)? = nil) {
        guard table == nil, let url else {
            onReady?()
            return
        }
        if let onReady { self.onReady.append(onReady) }
        guard !warming else { return }
        warming = true
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            let built = Self.parse(url)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                if self.table == nil { self.table = built }
                let waiting = self.onReady
                self.onReady = []
                waiting.forEach { $0() }
            }
        }
    }

    /// Give the table back; the next lookup reads it again. A no-op while a
    /// warm is in flight, and for a table built from entries.
    public func unload() {
        guard !warming, url != nil else { return }
        table = nil
    }

    /// What could follow `committed`, best first, at most `limit`, each once.
    /// Empty for text this table has nothing after — which is what dismisses
    /// the strip's suggestions.
    public func continuations(after committed: String, limit: Int = limit) -> [String] {
        let tail = Array(committed.suffix(Self.maxContext))
        guard !tail.isEmpty else { return [] }
        let table = load()
        var out: [String] = []
        var seen = Set<String>()
        for length in stride(from: tail.count, through: 1, by: -1) {
            let suffix = tail[(tail.count - length)...]
            guard let first = suffix.first, let row = table[first] else { continue }
            // What has to follow the first character for this row to continue
            // the suffix: nothing for the last character alone.
            let lead = String(suffix.dropFirst())
            for continuation in row.split(separator: " ") {
                guard continuation.count > lead.count, continuation.hasPrefix(lead) else {
                    continue
                }
                let next = String(continuation.dropFirst(lead.count))
                guard seen.insert(next).inserted else { continue }
                out.append(next)
                if out.count >= limit { return out }
            }
        }
        return out
    }

    private func load() -> [Character: String] {
        if let table { return table }
        if warming { return [:] }
        if !parsesOnLookup, url != nil {
            warm()
            return [:]
        }
        let built = url.map(Self.parse) ?? [:]
        table = built
        return built
    }

    /// Read the resource, line by line off a mapped file (`ResourceLines`).
    static func parse(_ url: URL) -> [Character: String] {
        var table: [Character: String] = [:]
        table.reserveCapacity(3_600)
        ResourceLines.forEach(in: url) { line in
            guard let tab = line.firstIndex(of: "\t"), tab > line.startIndex else { return }
            let key = line[line.startIndex..<tab]
            guard key.count == 1, let first = key.first else { return }
            let row = line[line.index(after: tab)...]
            guard !row.isEmpty else { return }
            table[first] = String(row)
        }
        ResourceLines.returnFreedPages()
        return table
    }
}
