import Foundation

/// The 注音 pane's phrase table: what a run of part-typed syllables could still
/// become.
///
/// This is what makes the pane predict rather than transcribe. Typing `ㄋㄏ` —
/// two lone 聲母, no vowels and no tones — must already offer 你好, the way the
/// system 注音 keyboard does; per-syllable data cannot answer that question at
/// all, because neither syllable is finished. So phrases are indexed by the
/// **first symbol of each of their first two syllables** (你好 ㄋㄧˇ ㄏㄠˇ lives
/// under `ㄋㄏ`), which is the least a user can have typed and still be asking
/// something, and every syllable is then matched slot by slot: the slots the
/// user has filled must be equal, the ones they have not are wildcards.
///
/// Rank is the file's order and nothing else — `scripts/gen-zhuyin-phrases.mjs`
/// scores every row (a damped corpus count, plus how ordinary the phrase's
/// characters are, plus a floor under everyday words a news corpus barely
/// contains) and writes them in that order, so this class carries no scores and
/// does no sorting.
///
/// **Loaded lazily and once**, like `ZhuyinDictionary` and for the same reason:
/// this runs inside a keyboard extension, which iOS jetsams far sooner than an
/// app, so nothing is read until the user has two syllables pending in the 注音
/// pane. A keyboard opened on the voice or QWERTY pane never pays for it. The
/// table is ~61,000 rows over ~1,400 index keys — a few megabytes resident, the
/// largest thing this process holds — and the file's own string is dropped as
/// soon as it is parsed. A missing resource answers no matches; a keyboard that
/// crashed because a file moved would be far worse than one that stops
/// predicting.
///
/// Readings are parsed at match time rather than up front, because only the
/// bucket under one key is ever looked at and pre-parsing all 61,000 would cost
/// memory for rows the user will never type.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class ZhuyinPhrases {
    /// A phrase the buffer could become, and how much of the buffer it answers.
    public struct Match: Equatable, Sendable {
        public let phrase: String
        /// The phrase's syllable count, which is also its character count — one
        /// Chinese character is one syllable, and the generator enforces it. May
        /// be **more** than the number of syllables typed: that is a prediction.
        public let span: Int

        public init(phrase: String, span: Int) {
            self.phrase = phrase
            self.span = span
        }
    }

    /// How many matches the bar is offered at most. The strip shows a handful
    /// and scrolls; past forty the user is faster retyping than reading.
    public static let matchLimit = 40

    /// The resource generated by `scripts/gen-zhuyin-phrases.mjs` from
    /// McBopomofo's `BPMFMappings.txt` (see `ios/THIRD-PARTY.md` — it carries
    /// libtabe's BSD notice as well as McBopomofo's MIT one).
    public static let bundled = ZhuyinPhrases(url: bundledURL)

    /// Internal rather than private so the tests can read the same file this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledURL: URL? {
        Bundle.module.url(forResource: "zhuyin-phrases", withExtension: "txt")
    }

    private struct Entry {
        let phrase: String
        /// Toned syllables separated by single spaces, exactly as the resource
        /// spells them.
        let reading: String
    }

    private var url: URL?
    private var index: [String: [Entry]]?
    /// A background build is on its way back to the main queue.
    private var warming = false

    /// Whether the table is in memory. Internal for the tests, which is where
    /// "did the warm arrive" is a question worth asking.
    var isWarm: Bool { index != nil }

    /// Build from rows given directly. This is how tests get a fixture whose
    /// order they control, rather than one the corpus decides.
    public init(entries: [(phrase: String, reading: String)]) {
        index = Self.indexed(entries.map { Entry(phrase: $0.phrase, reading: $0.reading) })
    }

    /// A `nil` url is a table that answers nothing.
    public init(url: URL?) {
        self.url = url
    }

    /// Build the table off the main thread, if it isn't built already.
    ///
    /// The first lookup parses 61,000 rows and indexes them — about 100 ms — and
    /// that must not land on the keystroke that finishes the user's second
    /// syllable, which is the first one to ask this class anything. The keyboard
    /// calls this when the 注音 pane becomes current, a beat earlier and idle.
    ///
    /// A lookup that arrives first still loads synchronously. At worst the file
    /// is parsed twice and the later table is dropped, which costs some work in
    /// a background thread and can never hand out a half-built one.
    ///
    /// Main thread, like everything else here: the guard and the store both run
    /// there, so two warms cannot race and a warm cannot overwrite a load.
    public func warm() {
        guard index == nil, !warming, let url else { return }
        warming = true
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            // Nothing on `self` is touched off the main queue — the parse is a
            // function of the URL alone.
            let built = Self.parse(url)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                // A synchronous load may have beaten this here. That table is
                // the same table; replacing it would only churn memory.
                if self.index == nil { self.index = built }
            }
        }
    }

    /// The phrases the pending syllables could still become, best first.
    ///
    /// Three groups, each in frequency order: the phrases that are exactly as
    /// long as what was typed, then the longer ones — those are the predictions,
    /// and they are what typing `ㄋㄏ` is really asking for — then the shorter
    /// ones that cover a prefix of the buffer, which is how a user who typed
    /// ahead still gets offered the word they started with.
    ///
    /// Empty for fewer than two syllables: one syllable is the dictionary's
    /// question, not this table's.
    public func matches(_ typed: [ZhuyinSyllable]) -> [Match] {
        guard typed.count >= 2, let key = Self.key(of: typed) else { return [] }
        guard let bucket = load()[key] else { return [] }

        var exact: [Match] = []
        var longer: [Match] = []
        var shorter: [Match] = []
        // A phrase listed under two readings can match both; the bar must not
        // show it twice.
        var seen = Set<String>()

        for entry in bucket {
            guard let span = Self.span(of: entry, matching: typed) else { continue }
            guard seen.insert(entry.phrase).inserted else { continue }
            let match = Match(phrase: entry.phrase, span: span)
            if span == typed.count {
                exact.append(match)
                // Nothing below the first group can reach the bar any more.
                if exact.count >= Self.matchLimit { break }
            } else if span > typed.count {
                longer.append(match)
            } else {
                shorter.append(match)
            }
        }
        return Array((exact + longer + shorter).prefix(Self.matchLimit))
    }

    // MARK: matching

    /// The entry's syllable count when every typed syllable matches, `nil`
    /// otherwise. An entry longer than the buffer must match all of it; one
    /// shorter must match its own length, which is the prefix case.
    private static func span(of entry: Entry, matching typed: [ZhuyinSyllable]) -> Int? {
        let parts = entry.reading.split(separator: " ", omittingEmptySubsequences: true)
        let span = parts.count
        guard span >= 2, entry.phrase.unicodeScalars.count == span else { return nil }
        for i in 0..<min(span, typed.count) {
            guard let syllable = ZhuyinSyllable.parse(String(parts[i])),
                matches(typed: typed[i], entry: syllable)
            else { return nil }
        }
        return span
    }

    /// Whether a part-typed syllable could still become an entry's syllable.
    ///
    /// Everything up to and including the last slot the user filled must be
    /// equal — **`nil` included**, so `ㄧㄡ`, which has no 聲母, does not match
    /// `ㄌㄧㄡˊ`, which has one. Everything after it is a wildcard, which is
    /// what makes a lone `ㄋ` match 你. A tone that was typed must match; one
    /// that wasn't is a wildcard too, and entry syllables always carry a tone
    /// because an unmarked reading is the first tone.
    private static func matches(typed: ZhuyinSyllable, entry: ZhuyinSyllable) -> Bool {
        if let tone = typed.tone, tone != entry.tone { return false }
        guard typed.initial == entry.initial else { return false }
        if typed.final != nil {
            return typed.medial == entry.medial && typed.final == entry.final
        }
        if typed.medial != nil { return typed.medial == entry.medial }
        return true
    }

    // MARK: the index

    /// The first symbol of each of the first two syllables — the key both a
    /// stored reading and a typed buffer are found under.
    private static func key(of typed: [ZhuyinSyllable]) -> String? {
        guard typed.count >= 2,
            let first = typed[0].initial ?? typed[0].medial ?? typed[0].final,
            let second = typed[1].initial ?? typed[1].medial ?? typed[1].final
        else { return nil }
        return String([first, second])
    }

    /// The same key read off a stored reading: the symbol after each space.
    /// Readings never begin with a tone mark, so the first symbol of a syllable
    /// is always one of the 37.
    private static func key(ofReading reading: String) -> String? {
        var key = ""
        var atSyllableStart = true
        for symbol in reading {
            if symbol == " " {
                atSyllableStart = true
                continue
            }
            guard atSyllableStart else { continue }
            key.append(symbol)
            atSyllableStart = false
            if key.count == 2 { return key }
        }
        return nil
    }

    private static func indexed(_ entries: [Entry]) -> [String: [Entry]] {
        var index: [String: [Entry]] = [:]
        for entry in entries {
            guard !entry.phrase.isEmpty, let key = key(ofReading: entry.reading) else { continue }
            index[key, default: []].append(entry)
        }
        return index
    }

    private func load() -> [String: [Entry]] {
        if let index { return index }
        // A failed read caches the empty index too, so a missing resource costs
        // one attempt rather than one per keystroke.
        let built = url.map(Self.parse) ?? [:]
        index = built
        return built
    }

    /// Read and index the resource. Static, and a function of the URL alone, so
    /// `warm` can run it on a background queue without touching this instance.
    private static func parse(_ url: URL) -> [String: [Entry]] {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return [:] }
        var entries: [Entry] = []
        entries.reserveCapacity(64_000)
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            guard !line.hasPrefix("#") else { continue }
            guard let tab = line.firstIndex(of: "\t") else { continue }
            let phrase = String(line[line.startIndex..<tab])
            let reading = String(line[line.index(after: tab)...])
            guard !phrase.isEmpty, !reading.isEmpty else { continue }
            entries.append(Entry(phrase: phrase, reading: reading))
        }
        // The file's string goes out of scope here.
        return indexed(entries)
    }
}
