import Foundation

/// The 注音 pane's candidate list: reading → the characters that read that way,
/// most frequent first.
///
/// Single characters only, on purpose. Phrase conversion is a different program
/// — a lattice over a phrase lexicon, plus a user dictionary to keep it honest —
/// and v1 of this pane does per-syllable input done properly instead. See
/// `docs/design/ios-voice-keyboard.md`.
///
/// **Loaded lazily and once.** This runs inside a keyboard extension, which iOS
/// jetsams far sooner than an app, so the resource is not touched until the user
/// actually finalizes a syllable: a keyboard opened on the voice or QWERTY pane
/// never pays for it. The table it builds is ~1,400 readings over ~27,000
/// characters — a few hundred kilobytes — and the file's own string is dropped
/// as soon as it is parsed.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class ZhuyinDictionary {
    /// The resource generated by `scripts/gen-zhuyin-dict.mjs` from McBopomofo's
    /// MIT-licensed data (see `ios/THIRD-PARTY.md`).
    public static let bundled = ZhuyinDictionary(url: bundledURL)

    /// Internal rather than private so the tests can read the same file this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledURL: URL? {
        Bundle.module.url(forResource: "zhuyin-dict", withExtension: "txt")
    }

    private var url: URL?
    private var table: [String: String]?

    /// Build from an already-parsed table. This is how tests get a fixture, and
    /// how a caller with its own data source stays out of the bundle.
    public init(entries: [String: String]) {
        table = entries
    }

    /// A `nil` url is a dictionary that answers nothing — a missing resource
    /// must degrade to "no candidates", never to a crash inside a keyboard.
    public init(url: URL?) {
        self.url = url
    }

    public func candidates(for syllable: ZhuyinSyllable) -> [String] {
        candidates(for: syllable.text)
    }

    /// The characters for a reading, most frequent first. Empty for a reading
    /// nothing is pronounced as — `ㄍㄧ` parses and has no candidates, and the
    /// pane says so by showing an empty bar rather than by refusing the keys.
    public func candidates(for reading: String) -> [String] {
        guard !reading.isEmpty, let row = load()[reading] else { return [] }
        // Every character in the source is exactly one Unicode scalar (the
        // generator enforces it), so the row needs no separator and no parsing
        // — including the ones outside the BMP, which is where the rarer
        // readings live.
        return row.unicodeScalars.map { String($0) }
    }

    /// The most likely character for a reading, which is what space commits and
    /// what starting the next syllable auto-commits.
    public func top(for syllable: ZhuyinSyllable) -> String? {
        guard let row = load()[syllable.text], let first = row.unicodeScalars.first else {
            return nil
        }
        return String(first)
    }

    private func load() -> [String: String] {
        if let table { return table }
        var entries: [String: String] = [:]
        if let url, let text = try? String(contentsOf: url, encoding: .utf8) {
            entries.reserveCapacity(1500)
            for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
                guard !line.hasPrefix("#") else { continue }
                guard let tab = line.firstIndex(of: "\t") else { continue }
                let reading = String(line[line.startIndex..<tab])
                let row = String(line[line.index(after: tab)...])
                guard !reading.isEmpty, !row.isEmpty else { continue }
                entries[reading] = row
            }
        }
        // The file's string goes out of scope here. A failed read caches the
        // empty table too, so a missing resource costs one attempt rather than
        // one per keystroke.
        table = entries
        return entries
    }
}
