import Foundation

/// The 注音 pane's candidate list: reading → the characters that read that way,
/// most frequent first.
///
/// Two kinds of key live in the one table. A plain key is a reading **with** its
/// tone mark, which is what the user has once a tone key is pressed. A key
/// prefixed `~` is the same reading with no tone at all — the union of its five
/// tone rows — because the pane has to offer candidates while a syllable is
/// still being typed, and the first tone is written with no mark, so `ㄋㄧ`
/// already means ㄋㄧˉ and cannot also stand for "ㄋㄧ, tone not typed yet". The
/// prefix is not a 注音 symbol, so the two kinds cannot collide.
///
/// Single characters only. Phrases live in `ZhuyinPhrases`, which answers first
/// when two or more syllables are pending; this table is the per-syllable
/// fallback behind it and the whole answer for a lone syllable. See
/// `docs/design/ios-voice-keyboard.md`.
///
/// **One wrong symbol still answers.** A syllable's candidates are its own row
/// and then a bounded tail from the rows of the syllables it differs from by one
/// `ZhuyinFuzzy` substitution — 模糊音 or an adjacent key — so `ㄗㄨㄥ` offers
/// 從, 總 and 宗 first and 中 after them. The table itself is unchanged: the
/// variants are more lookups into it, not more rows.
///
/// **Loaded lazily and once.** This runs inside a keyboard extension, which iOS
/// jetsams far sooner than an app, so the resource is not touched until the user
/// types into the 注音 pane: a keyboard opened on the voice or QWERTY pane never
/// pays for it. The table it builds is ~1,400 readings plus ~430 toneless rows
/// over ~52,000 characters — a few hundred kilobytes — and the file's own string
/// is dropped as soon as it is parsed.
///
/// Not thread-safe, and it doesn't need to be: keys arrive on the main thread.
public final class ZhuyinDictionary {
    /// The resource generated by `scripts/gen-zhuyin-dict.mjs` from McBopomofo's
    /// MIT-licensed data (see `ios/THIRD-PARTY.md`).
    public static let bundled = ZhuyinDictionary(url: bundledURL)

    /// Internal rather than private so the tests can read the same file this
    /// reads — `Bundle.module` in a test target is the *test* bundle, which is
    /// not where the package's resources live.
    static var bundledURL: URL? {
        Bundle.module.url(forResource: "zhuyin-dict", withExtension: "txt")
    }

    private var url: URL?
    private var table: [String: String]?
    /// A background build is on its way back to the main queue.
    private var warming = false

    /// Whether the table is in memory. Internal for the tests, which is where
    /// "did the warm arrive" is a question worth asking.
    var isWarm: Bool { table != nil }

    /// Build from an already-parsed table. This is how tests get a fixture, and
    /// how a caller with its own data source stays out of the bundle.
    public init(entries: [String: String]) {
        table = entries
    }

    /// A `nil` url is a dictionary that answers nothing — a missing resource
    /// must degrade to "no candidates", never to a crash inside a keyboard.
    public init(url: URL?) {
        self.url = url
    }

    /// Build the table off the main thread, if it isn't built already.
    ///
    /// Same bargain as `ZhuyinPhrases.warm()`, and the keyboard calls them
    /// together when the 注音 pane becomes current: the cost of the first read
    /// belongs to a moment the user is not waiting on a key. A lookup that
    /// arrives first still loads synchronously.
    ///
    /// Main thread, like everything else here: the guard and the store both run
    /// there, so two warms cannot race and a warm cannot overwrite a load.
    public func warm() {
        guard table == nil, !warming, let url else { return }
        warming = true
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            // Nothing on `self` is touched off the main queue — the parse is a
            // function of the URL alone.
            let built = Self.parse(url)
            DispatchQueue.main.async {
                guard let self else { return }
                self.warming = false
                // A synchronous load may have beaten this here; that table is
                // the same table.
                if self.table == nil { self.table = built }
            }
        }
    }

    /// The characters for a toned syllable: its own row, then — unless `fuzzy`
    /// is off — the characters of the syllables it could have been meant as.
    /// See `withVariants` for the order and the bound.
    public func candidates(for syllable: ZhuyinSyllable, fuzzy: Bool = true) -> [String] {
        withVariants(of: syllable, fuzzy: fuzzy) { $0.text }
    }

    /// The characters for a syllable **ignoring its tone**, which is what the
    /// bar shows while the user is still typing one. The key is built from the
    /// slots rather than from `text`, so a syllable that already carries a tone
    /// answers the toneless row too — re-toning is allowed, and asking "what
    /// could this still become" has to survive it. Fuzzy as `candidates` is.
    public func tonelessCandidates(for syllable: ZhuyinSyllable, fuzzy: Bool = true) -> [String] {
        withVariants(of: syllable, fuzzy: fuzzy) { variant in
            var key = "~"
            if let initial = variant.initial { key.append(initial) }
            if let medial = variant.medial { key.append(medial) }
            if let final = variant.final { key.append(final) }
            // A bare `~` is not a key; `candidates(for:)` answers it with nothing.
            return key.count > 1 ? key : ""
        }
    }

    /// How many characters each fuzzy variant may add. A slip is asking for the
    /// word the user meant, which is among that reading's commonest characters,
    /// not for its whole row — and the strip draws every candidate it is given,
    /// so fourteen variants' full rows (toneless rows run to 441 characters)
    /// would be well over a thousand buttons on a keystroke.
    public static let fuzzyPerVariant = 8

    /// The exact row first, untouched, then for each `ZhuyinFuzzy.variants` in
    /// order its leading characters that are not already there.
    ///
    /// Exact first is the whole contract: a correctly typed syllable must read
    /// exactly as it did before error tolerance existed, so a fuzzy character can
    /// only ever come *after* every exact one, and `top` — the first element — is
    /// the exact top whenever there is one. With no exact row at all the first
    /// fuzzy character is the top, which is what lets a mistyped syllable still
    /// commit a character on return rather than its raw 注音.
    ///
    /// A variant's row is read as raw scalars and abandoned after its first few
    /// new characters, rather than split in full: a toneless row can be hundreds
    /// long and only `fuzzyPerVariant` of it is wanted.
    private func withVariants(
        of syllable: ZhuyinSyllable, fuzzy: Bool, key: (ZhuyinSyllable) -> String
    ) -> [String] {
        var out = candidates(for: key(syllable))
        guard fuzzy else { return out }
        var seen: Set<String>?
        for variant in ZhuyinFuzzy.variants(of: syllable) {
            let reading = key(variant)
            guard !reading.isEmpty, let row = load()[reading] else { continue }
            if seen == nil { seen = Set(out) }
            var added = 0
            for scalar in row.unicodeScalars {
                guard added < Self.fuzzyPerVariant else { break }
                let character = String(scalar)
                guard seen?.insert(character).inserted == true else { continue }
                out.append(character)
                added += 1
            }
        }
        return out
    }

    /// The characters for a reading, most frequent first. Empty for a reading
    /// nothing is pronounced as — `ㄍㄧ` parses and has no candidates, and the
    /// pane says so by showing an empty bar rather than by refusing the keys.
    public func candidates(for reading: String) -> [String] {
        guard !reading.isEmpty, let row = load()[reading] else { return [] }
        // Every character in the source is exactly one Unicode scalar (the
        // generator enforces it), so the row needs no separator and no parsing
        // — including the ones outside the BMP, which is where the rarer
        // readings live.
        return row.unicodeScalars.map { String($0) }
    }

    /// The most likely character for a reading — the exact row's first, with no
    /// fuzzy fallback. The composer takes its top from `candidates` instead, which
    /// is exact-first and falls back to a variant's.
    public func top(for syllable: ZhuyinSyllable) -> String? {
        guard let row = load()[syllable.text], let first = row.unicodeScalars.first else {
            return nil
        }
        return String(first)
    }

    private func load() -> [String: String] {
        if let table { return table }
        // A failed read caches the empty table too, so a missing resource costs
        // one attempt rather than one per keystroke.
        let entries = url.map(Self.parse) ?? [:]
        table = entries
        return entries
    }

    /// Read the resource. Static, and a function of the URL alone, so `warm`
    /// can run it on a background queue without touching this instance.
    private static func parse(_ url: URL) -> [String: String] {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return [:] }
        var entries: [String: String] = [:]
        entries.reserveCapacity(2000)
        // `~` rows need no special case: the key is read verbatim and the prefix
        // is not a 注音 symbol, so nothing else can claim it.
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            guard !line.hasPrefix("#") else { continue }
            guard let tab = line.firstIndex(of: "\t") else { continue }
            let reading = String(line[line.startIndex..<tab])
            let row = String(line[line.index(after: tab)...])
            guard !reading.isEmpty, !row.isEmpty else { continue }
            entries[reading] = row
        }
        // The file's string goes out of scope here.
        return entries
    }
}
