//! macOS: the general NSPasteboard. Every call here runs on the main thread —
//! the insert and copy commands are synchronous (Tauri runs those there), and
//! the restore timer hops onto it — inside its own autorelease pool, so a
//! large image's data does not wait for the run loop to be freed.

// The `objc` 0.2 macros emit `cfg(cargo-clippy)` checks newer compilers warn on.
#![allow(unexpected_cfgs)]

use core_foundation::base::TCFType;
use core_foundation::string::CFString;
use objc::rc::autoreleasepool;
use objc::runtime::Object;
use objc::{class, msg_send, sel, sel_impl};

use super::{is_concealed, is_saved_type, Pasteboard, SnapshotBudget};

/// NSPasteboardTypeString's UTI; spelled out rather than linking the extern
/// NSString constant.
const PLAIN_TEXT: &str = "public.utf8-plain-text";

/// The nspasteboard.org markers for data that is on the pasteboard only
/// briefly (transient) and that the user did not copy (auto-generated).
/// Clipboard managers that honour them (Maccy, Paste, Alfred, Raycast, …) do
/// not record the dictation. The data is irrelevant; the type is the marker.
const TRANSIENT: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";

/// `NSPasteboardContentsCurrentHostOnly`: keep the dictation off Universal
/// Clipboard, so it does not turn up on the user's other devices — the
/// counterpart of Windows' "do not upload to the cloud clipboard".
const CURRENT_HOST_ONLY: usize = 1 << 0;

/// Every item on the pasteboard, each as its (type, data) pairs in the order
/// the item lists them — an image copied from a browser is one item with a
/// TIFF, a PNG and an HTML rendering of the same thing; a Finder copy of three
/// files is three items.
pub type Snapshot = Vec<Vec<(String, Vec<u8>)>>;

pub struct SystemPasteboard;

impl Pasteboard for SystemPasteboard {
    type Snapshot = Snapshot;

    /// Best effort by nature: reading a type makes the app that copied it
    /// produce that data now if it only promised it, and a promise its owner
    /// does not keep (it quit; a file promise) has nothing to save. So only
    /// an allow-list of plain types is read (`is_saved_type`), within a
    /// [`SnapshotBudget`]: this runs on the main thread, every window and the
    /// paste wait for it, and a read already running cannot be cut short.
    fn snapshot(&mut self) -> Result<Snapshot, String> {
        autoreleasepool(|| unsafe {
            let pb = general()?;
            let items: *mut Object = msg_send![pb, pasteboardItems];
            let items: Vec<(*mut Object, Vec<(*mut Object, String)>)> = objects(items)
                .into_iter()
                .map(|item| {
                    let types: *mut Object = msg_send![item, types];
                    let types = objects(types)
                        .into_iter()
                        .filter_map(|t| Some((t, string(t)?)))
                        .collect();
                    (item, types)
                })
                .collect();
            // Checked on every item before a single byte is read (see
            // CONCEALED_TYPE).
            if items
                .iter()
                .any(|(_, types)| is_concealed(types.iter().map(|(_, name)| name.as_str())))
            {
                log::info!("voice-typing: the clipboard holds a concealed entry; it is cleared, not restored");
                return Ok(Vec::new());
            }
            let mut budget = SnapshotBudget::start();
            let mut saved = Vec::with_capacity(items.len());
            for (item, types) in &items {
                let item = *item;
                let names: Vec<&str> = types.iter().map(|(_, name)| name.as_str()).collect();
                let mut entries = Vec::with_capacity(types.len());
                for (ty, name) in types {
                    if !is_saved_type(name, &names) {
                        continue;
                    }
                    budget.before_read()?;
                    let data: *mut Object = msg_send![item, dataForType: *ty];
                    if data.is_null() {
                        continue;
                    }
                    let len: usize = msg_send![data, length];
                    budget.take(len)?;
                    entries.push((name.clone(), bytes(data)));
                }
                if !entries.is_empty() {
                    saved.push(entries);
                }
            }
            Ok(saved)
        })
    }

    fn write_transient(&mut self, text: &str) -> Result<(), String> {
        let entries = [
            (PLAIN_TEXT, text.as_bytes()),
            (TRANSIENT, &[][..]),
            (AUTO_GENERATED, &[][..]),
        ];
        autoreleasepool(|| unsafe { write(general()?, [entries], CURRENT_HOST_ONLY) })
    }

    /// `clearContents` → `setString:forType:`; CFString is toll-free bridged
    /// to NSString, so it is passed straight through.
    fn write_plain(&mut self, text: &str) -> Result<(), String> {
        autoreleasepool(|| unsafe {
            let pb = general()?;
            let _: isize = msg_send![pb, clearContents];
            let value = CFString::new(text);
            let ty = CFString::new(PLAIN_TEXT);
            let ok: bool = msg_send![pb, setString: obj(&value) forType: obj(&ty)];
            if ok {
                Ok(())
            } else {
                Err("pasteboard rejected string".into())
            }
        })
    }

    /// `changeCount`. With no pasteboard, a value no write produces, so the
    /// restore that compares against it is skipped.
    fn change_mark(&mut self) -> i64 {
        unsafe {
            match general() {
                Ok(pb) => {
                    let count: isize = msg_send![pb, changeCount];
                    count as i64
                }
                Err(_) => i64::MIN,
            }
        }
    }

    /// NSPasteboard has no lock to hold across the check, so `changeCount`
    /// is compared right before the write clears it, on the main thread: a
    /// copy from another app would have to land between those two calls.
    ///
    /// The restored contents go up marked auto-generated and current-host-only:
    /// they are what the user copied before, which clipboard managers already
    /// recorded and Universal Clipboard already carried when they copied it.
    /// Unmarked, the restore read as a fresh copy, and a clipboard manager
    /// listed the same entry again after every dictation.
    fn restore_if_unchanged(&mut self, snapshot: &Snapshot, mark: i64) -> Result<bool, String> {
        let items = snapshot.iter().enumerate().map(|(i, item)| {
            let mut entries: Vec<(&str, &[u8])> = item
                .iter()
                .map(|(ty, data)| (ty.as_str(), data.as_slice()))
                .collect();
            // The marker is a type on the pasteboard, so one item carries it.
            if i == 0 {
                entries.push((AUTO_GENERATED, &[][..]));
            }
            entries
        });
        autoreleasepool(|| unsafe {
            let pb = general()?;
            let count: isize = msg_send![pb, changeCount];
            if count as i64 != mark {
                return Ok(false);
            }
            write(pb, items, CURRENT_HOST_ONLY).map(|()| true)
        })
    }
}

/// `NSPasteboard.generalPasteboard`.
unsafe fn general() -> Result<*mut Object, String> {
    let pb: *mut Object = msg_send![class!(NSPasteboard), generalPasteboard];
    if pb.is_null() {
        Err("no general pasteboard".into())
    } else {
        Ok(pb)
    }
}

/// A CFString as the NSString it is toll-free bridged to.
fn obj(s: &CFString) -> *const Object {
    s.as_concrete_TypeRef() as *const Object
}

/// The objects of an NSArray (borrowed: the array, autoreleased, keeps them).
unsafe fn objects(array: *mut Object) -> Vec<*mut Object> {
    if array.is_null() {
        return Vec::new();
    }
    let count: usize = msg_send![array, count];
    (0..count)
        .map(|i| {
            let o: *mut Object = msg_send![array, objectAtIndex: i];
            o
        })
        .collect()
}

/// An NSString's contents. It is a +0 getter's result, so a get-rule
/// reference — the create rule would over-release it.
unsafe fn string(ns: *mut Object) -> Option<String> {
    if ns.is_null() {
        return None;
    }
    Some(CFString::wrap_under_get_rule(ns as _).to_string())
}

/// An NSData's bytes, copied out.
unsafe fn bytes(data: *mut Object) -> Vec<u8> {
    let len: usize = msg_send![data, length];
    let ptr: *const u8 = msg_send![data, bytes];
    if len == 0 || ptr.is_null() {
        return Vec::new();
    }
    std::slice::from_raw_parts(ptr, len).to_vec()
}

/// Clear the pasteboard and write one NSPasteboardItem per entry list (none:
/// the pasteboard is just cleared). Through items rather than the
/// pasteboard's own setters, so several items — and several types on each —
/// go up in one write. `options` are NSPasteboardContentsOptions for the new
/// contents.
unsafe fn write<'a, I, E>(pb: *mut Object, items: I, options: usize) -> Result<(), String>
where
    I: IntoIterator<Item = E>,
    E: IntoIterator<Item = (&'a str, &'a [u8])>,
{
    // `clearContents` with options (macOS 10.12+).
    let _: isize = msg_send![pb, prepareForNewContentsWithOptions: options];
    let array: *mut Object = msg_send![class!(NSMutableArray), array];
    for entries in items {
        let item: *mut Object = msg_send![class!(NSPasteboardItem), new];
        for (ty, data) in entries {
            let ty = CFString::new(ty);
            let data: *mut Object =
                msg_send![class!(NSData), dataWithBytes: data.as_ptr() length: data.len()];
            let _: bool = msg_send![item, setData: data forType: obj(&ty)];
        }
        // The array retains the item; `new` handed us our own reference.
        let _: () = msg_send![array, addObject: item];
        let _: () = msg_send![item, release];
    }
    let count: usize = msg_send![array, count];
    if count == 0 {
        return Ok(());
    }
    let ok: bool = msg_send![pb, writeObjects: array];
    if ok {
        Ok(())
    } else {
        Err("pasteboard refused the items".into())
    }
}
